### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by krishnakanthpps** [ccoombsesmail/Fidget#8]
Hi.. Great work.

Looks more like Caffeine.tv's clone. 

Can you help me set this up? I have a very different use case and have not been able to Go Live from browser. 

Can you provide installation instructions?

Regards.

**Comment by ccoombsesmail** [comment]
Oh whoops sorry for the late response. It should work if you:

- bundle install
- npm install
- start postgres
- rails s
- npm run webpack

I have only really tested it on Chrome and Firefox btw

**Comment by krishnakanthpps** [comment]
Thank you.
